SIM = icarus

TOPLEVEL_LANG = verilog

SOURCES_DIR = ../../src

VERILOG_SOURCES = $(SOURCES_DIR)/dual_port_fifo.sv $(SOURCES_DIR)/gray2bin.sv  $(SOURCES_DIR)/bin2gray.sv

TOPLEVEL = dual_port_fifo

MODULE = dual_port_fifo

include $(shell cocotb-config --makefiles)/Makefile.sim




