SIM = icarus

TOPLEVEL_LANG = verilog

SOURCES_DIR = ../../src

VERILOG_SOURCES = $(SOURCES_DIR)/bin2gray.sv $(SOURCES_DIR)/gray2bin.sv gray_tb.sv

TOPLEVEL = gray_tb

MODULE = gray_tb

include $(shell cocotb-config --makefiles)/Makefile.sim




